@startuml NodeAccPanel
!include ../../../settings.pu

class NodeAccPanel {
    props name:string
    props expanded:boolean
    props nodetypes:string[]
    props handleChange:(panel: string) => (event: React.SyntheticEvent, isExpanded: boolean) => void
  ---
  onDragStart = (event: React.DragEvent<HTMLDivElement>, nodeType: string) => void
  render(): JSX
}

class Item{
  styled(Paper)
}

NodeAccPanel --|> Item
note right
    This is a standalone function.
    It is not a part of any class.
end note

@enduml