@startuml NodeDisplayAccPanel
!include ../../../settings.pu

class NodeDisplayAccPanel {
  props name:string
  props expanded:boolean
  props handleChange:(panel: string) => (event: React.SyntheticEvent, isExpanded: boolean)=>void
  props Nodes:Node[]
  props setNodes:(Nodes:Node[])=>void
  ---
  render(): JSX
}
@enduml