@startuml BackGroundNode
!include ../../settings.pu

class BackGroundNode {
  props NodeProps
  render(): JSX
}

class Item{
  styled(Paper)
}

BackGroundNode --|> Item
note right
    This is a standalone function.
    It is not a part of any class.
end note

@enduml