@startuml ReactantNode
!include ../../settings.pu

class ReactantNode {
  props NodeProps
  render(): JSX
}

class Item{
  styled(Paper)
}

ReactantNode --|> Item
note right
    This is a standalone function.
    It is not a part of any class.
end note

@enduml