@startuml EdgeDialog
!include ../../settings.pu

class EdgeDialog {
  props open: boolean
  props onClose: (newedge?: Edge) => void
  props edge:Edge
  ....
  state [tmpEdge, setTmpEdge] = useState<Edge>(props.edge)
  ---
  handleClose=(v:string)
  handleOnChange=(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,k: string)
  handleOnValueChange=(values: NumberFormatValues,k: string)
  render(): JSX
}
@enduml