@startuml NodeDialog
!include ../../settings.pu

class NodeDialog {
  props open: boolean,
  props onClose: (newnode?: Node) => void,
  props node:Node
  props nodes:Node[]
  ....
  state [tmpNode, setTmpNode] = useState<Node>(props.node)
  ---
  handleClose=(v:string)
  handleOnChange=(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,k: string)
  handleOnValueChange=(values: NumberFormatValues,k: string)
  handleOnCheckedChange=(e: React.ChangeEvent<HTMLInputElement>,k:string)
  render(): JSX
}
@enduml