@startuml SideBarMain
!include ../../settings.pu

class SideBarMain {
  props NodeTypeKeys:string[],
  props Nodes:Node[]
  props Edges:Edge[],
  props setNodes:(Nodes:Node[])=>void,
  props setEdges:(Edges:Edge[])=>void,
  ....
  - panelObj:{[key:string]:string}(Object.assign({},...Object.keys((panelObj)).map((p)=>({[p]:false}))))
  ....
  state [expanded, setExpanded] = React.useState<Panels>
  ---
  handleChange = React.useCallback((panel: string) => void
  render(): JSX
}
@enduml