@startuml FileHandler
!include ../settings.pu

package FileHandler[
  ExportExcel=async(e:{ preventDefault: () => void; },NODES:Node[],EDGES:Edge[],SCHEMEDATA:{[key:string]:string}|null) => void
  ---
  ImportExpDataExcel=(EVENT:ChangeEvent<HTMLInputElement>) => void
]

@enduml